// backend/src/routes/cart.js
// ⭐ SERVERLESS-READY + SECURITY-HARDENED

const express = require('express');
const router = express.Router();
const CartController = require('../controllers/cartController');
const { verifyCustomerToken, optionalCustomerAuth } = require('../middleware/userAuth');

// ========================================
// CART ROUTES
// Base path: /api/cart
// ========================================

/**
 * Cart Authentication Strategy:
 * 
 * 1. AUTHENTICATED USERS (has JWT token):
 *    - Cart tied to user_id (persistent across devices)
 *    - Uses verifyCustomerToken middleware
 * 
 * 2. GUEST USERS (no JWT token):
 *    - Cart tied to session_id (from frontend localStorage)
 *    - Session ID validated but not authenticated
 *    - Converted to user cart on login via POST /merge
 * 
 * Security:
 * - User IDs come from verified JWT tokens ONLY
 * - Session IDs are UUIDs generated by frontend
 * - No user impersonation possible
 */

/**
 * @route   GET /api/cart
 * @desc    Get current user's cart or guest cart
 * @access  Public (uses optional auth)
 * @headers x-session-id - Guest session UUID (if not logged in)
 * @returns { items: [], total_price: number, total_items: number }
 */
router.get('/', optionalCustomerAuth, CartController.getCart);

/**
 * @route   POST /api/cart/items
 * @desc    Add bundle to cart
 * @access  Public (uses optional auth)
 * @body    { bundle_id: uuid, quantity: number }
 */
router.post('/items', optionalCustomerAuth, CartController.addToCart);

/**
 * @route   POST /api/cart/products
 * @desc    Add individual product to cart
 * @access  Public (uses optional auth)
 * @body    { product_id: uuid, variant_id?: uuid, quantity: number }
 */
router.post('/products', optionalCustomerAuth, CartController.addProductToCart);

/**
 * @route   PATCH /api/cart/items/:id
 * @desc    Update cart item quantity
 * @access  Public (uses optional auth)
 * @body    { quantity: number }
 */
router.patch('/items/:id', optionalCustomerAuth, CartController.updateCartItem);

/**
 * @route   DELETE /api/cart/items/:id
 * @desc    Remove item from cart
 * @access  Public (uses optional auth)
 */
router.delete('/items/:id', optionalCustomerAuth, CartController.removeCartItem);

/**
 * @route   DELETE /api/cart
 * @desc    Clear entire cart
 * @access  Public (uses optional auth)
 */
router.delete('/', optionalCustomerAuth, CartController.clearCart);

/**
 * @route   POST /api/cart/merge
 * @desc    Merge guest cart into authenticated user cart
 * @access  Private (Customer only - requires login)
 * @body    { session_id: uuid }
 * @note    Called automatically after login/register
 */
router.post('/merge', verifyCustomerToken, CartController.mergeCarts);

module.exports = router;